# See LICENSE file for the license details of MIT
# Copyright 2020 Marno van der Maas

#This file is necessary when using this as a sub repository in riscv-linux

obj-y := instructions.o praesidioenclave.o mailbox.o

ccflags-y += -Idrivers/praesidio/praesidio-software/lib
